[[redirects]]
	from = "/codeofconduct"
	to = "/assets/dh18_code_of_conduct.pdf"
	status = 302

[[redirects]]
	from = "/sponsorshipdeck"
	to = "https://drive.google.com/file/d/1-XTLcm9eFmUsyVWDA9PQOrBvniFXPFmr/view"
	status = 302

[[redirects]]
	from = "/visaletter"
	to = "https://ducompsoc.typeform.com/to/Xr4WLQ"
	status = 302

[[redirects]]
	from = "/fathippo"
	to = "https://deliveroo.co.uk/menu/durham/durham/fat-hippo-durham?postcode=DH13LE"
	status = 301


[dev]
	publish = "dist/"
